INSERT INTO person (FIRST_NAME, LAST_NAME, CREATED_DATETIME, UPDATED_DATETIME) VALUES ('Axel', 'Triple', now(), now());
INSERT INTO person (FIRST_NAME, LAST_NAME, CREATED_DATETIME, UPDATED_DATETIME) VALUES ('Mr. ', 'Foo', now(), now());
INSERT INTO person (FIRST_NAME, LAST_NAME, CREATED_DATETIME, UPDATED_DATETIME) VALUES ('Ms. ', 'Bar', now(), now());
INSERT INTO person (FIRST_NAME, LAST_NAME, CREATED_DATETIME, UPDATED_DATETIME) VALUES ('Mrs. ', 'Dunst',  now(), now());